### ISSUE TITLE
Unsupported media type \"\" in request.

### ISSUE THREAD

**Issue by keH1** [affiliateforge/php-admitad-api#10]
При отправке запроса и попытке получения купонов согласно коду из документации https://test-tickets-gate--1.org.readthedocs.build/en/1/overview/index.html

Получаем ответ вида: 
```
[
  "detail" => "Unsupported media type "" in request."
  "status_code" => 415
]
```

После небольшого ресеча, через постман, выяснилось что это происходит из-за отсутствующего по умолчанию в библиотеке заголовка 
`Content-Type: application/x-www-form-urlencoded`

**Comment by kvatra** [comment]
@keH1 Привет!
А вы прям из примера код используете или какой то свой запрос? Полный код бы того, что вы делаете, если не из примера. 
Также документацию уже стоит смотреть на https://php-admitad-api--9.org.readthedocs.build/en/9/index.html

https://test-tickets-gate--1.org.readthedocs.build/en/1/overview/index.html - это была временная, уже не актуальна и не поддерживается.

**Comment by keH1** [comment]
> @keH1 Привет! А вы прям из примера код используете или какой то свой запрос? Полный код бы того, что вы делаете, если не из примера. Также документацию уже стоит смотреть на https://php-admitad-api--9.org.readthedocs.build/en/9/index.html
> 
> https://test-tickets-gate--1.org.readthedocs.build/en/1/overview/index.html - это была временная, уже не актуальна и не поддерживается.

Да я прямо скопипастил код из документации добавил заголовок и все взлетело, все как описал, версия либы 1.0.3

**Comment by kvatra** [comment]
@keH1 Тут, видимо, дело в подключаемом http-client'e. У меня локально все ок и без этого header'a. Можешь написать плез, какой вы установили себе в итоге?

Тем не менее, добавил этот header по умолчанию, у меня не сломалось. Сделал релиз - 1.0.4 (https://github.com/affiliateforge/php-admitad-api/releases/tag/v1.0.4)

Issue закрываю

**Comment by keH1** [comment]
> @keH1 Тут, видимо, дело в подключаемом http-client'e. У меня локально все ок и без этого header'a. Можешь написать плез, какой вы установили себе в итоге?
> 
> Тем не менее, добавил этот header по умолчанию, у меня не сломалось. Сделал релиз - 1.0.4 (https://github.com/affiliateforge/php-admitad-api/releases/tag/v1.0.4)
> 
> Issue закрываю

Вообще пакет на ларавель ставлю 11 там по умолчанию под капотом вроде как Газл, но у вас же пакет использует свой клиент который подтягивается тоже, если я верно понимаю, в любом случае спасибо за реакцию)
