### ISSUE TITLE
Не учтено что из Адмитада может вернутся null в description

### ISSUE THREAD

**Issue by keH1** [affiliateforge/php-admitad-api#11]
Не учтено что АПИ адмитада может в getDescription вернуть null в данном классе `vendor/affiliateforge/php-admitad-api/src/Api/Endpoints/Coupons/Entities/Coupon.php:29`

Из-за чего вызывается ошибка по строке указанной выше.

**Comment by kvatra** [comment]
Поправил в релизе 1.0.4 ((https://github.com/affiliateforge/php-admitad-api/releases/tag/v1.0.4)

Issue закрываю
